apiVersion: v1
kind: Service
metadata:
  name: sample-deploy-service
spec:
  selector: 
    app: deploy-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deploy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-app
      tier: backend
  template:
    metadata: 
      labels:
        app: deploy-app
        tier: backend
    spec: 
      containers:
        - name: sample-node
          image: raphaelmans/kub-sample-deploy
        # - name: ...
        #   image: ...
